### ISSUE TITLE
Force paste text as "plain text"

### ISSUE THREAD

**Issue by mikehudak** [stefanvermaas/yellow-text#34]
How to force paste text into textarea as "plain text" ?

I have here snippet

```
editor.addEventListener("paste", function(e) {
    // cancel paste
    e.preventDefault();

    // get text representation of clipboard
    var text = e.clipboardData.getData("text/plain");

    // insert text manually
    document.execCommand("insertHTML", false, text);
});
```

Where to put it ?

**Comment by stefanvermaas** [comment]
Hi @mikehudak,

I don't have an answer strait away. I'll be looking into this. Could you give some more information about what you tried to achieve and where you want to "put" the code?

Cheers!

**Comment by m1kesk** [comment]
deprecated
