### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dandv** [stefanvermaas/yellow-text#36]
Would love to see an online demo.

**Comment by stefanvermaas** [comment]
Hi @dandv, 

I've been very busy last year, so I had no possibility to actively maintain it. I'm planning to start refactoring and adding new features in Q1 of 2016. I don't have an online demo right now, but you could download the GIT repo and look in the demo folder.

Hope this helps you. Cheers!

**Comment by dandv** [comment]
Thanks Stefan. I was [comparing rich text editors](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md).

**Comment by stefanvermaas** [comment]
:+1:
