### ISSUE TITLE
¿Cómo obtengo el valor del area de texto? 

### ISSUE THREAD

**Issue by CesarsEren** [stefanvermaas/yellow-text#40]
$("#js-textarea").val()  NO FUNCIONA

**Comment by stefanvermaas** [comment]
Hi @CesarsEren,

My Spanish isn't very good, so I hope you're also good with me replying in English ;)! You can use the `.getContentFromEditor()` for this. 

```javascript
const editor = $('#js-textarea').YellowText();
console.log(editor.getContentFromEditor());
```

**Comment by CesarsEren** [comment]
Thank you very much in the end I solved it by sending the form, but with this information that you give me I will send it with Ajax, Thank you.

**Comment by stefanvermaas** [comment]
Wonderful! Great to hear it worked out for you!
